### ISSUE TITLE
scanning caught an error: bufio.Scanner: token too long

### ISSUE THREAD

**Issue by patroza** [humanlogio/humanlog#53]
Hi,

I have a long json payload in logfmt value, and I run into token too long.
Could you please increase the buffer, make it configurable, and perhaps at least catch the particular error and instead of crashing, mark the field as error and continue?

I found some background on the error: https://stackoverflow.com/a/37455465

**Comment by aybabtme** [comment]
@patroza do you mind me asking how long is the string you're dealing with?

**Comment by patroza** [comment]
@aybabtme could be a few MB, it's a json payload body while debugging.

I noticed that the latest versions have truncation enabled by default,
interestingly enough, when humanlog is installed with brew on mac, it registers as version `devel`,
and I have an older version than when you `install.sh`.

This was super confusing as a co-worker installed it on linux via `install.sh` and I had it via brew, and he was seeing truncation, and I wasn't :)

**Comment by aybabtme** [comment]
@patroza which tap did you use for installing `humanlog`? If you still use `aybabtme/homebrew-tap`, it has moved to `humanlogio/homebrew-tap` :)
