### ISSUE TITLE
Installation script doesn't work on "aarch64"

### ISSUE THREAD

**Issue by allir** [humanlogio/humanlog#61]
Installing in a Linux VM on ARM MacBook. `uname -m` returns "aarch64" which then returns an error from the api call to <https://api.humanlog.io/api/releases/humanlog> in the installation script.

Example of manually reproducing:
```shell
$ curl -s --data "{\"os\":\"${os}\",\"arch\":\"${arch}\"}" https://api.humanlog.io/api/releases/humanlog
oups, something went wrong serving your request
```

**Comment by adriangalilea** [comment]
Had the same issue.

**Comment by aybabtme** [comment]
should be fixed now:

```
$ curl -s --data '{"os":"linux","arch":"aarch64"}' https://api.humanlog.io/api/releases/humanlog
https://github.com/humanlogio/humanlog/releases/download/v0.7.7/humanlog_0.7.7_linux_arm64.tar.gz
```

sorry it took so long to get to it, and thanks for the report @allir and @adriangalilea
